services:
  app:
    build: .
    container_name: transcription-app
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
    environment:
      - FLASK_ENV=production
      - MODEL_PATH=/app/models/faster-whisper-medium-id
      - DEVICE=cpu
      - COMPUTE_TYPE=int8
    restart: unless-stopped
