services:
  app:
    build: .
    container_name: transcription-app
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
    environment:
      - FLASK_ENV=production
      - MODEL_PATH=/app/models/faster-whisper-medium-id
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/transcripts
      - DEVICE=cpu
      - COMPUTE_TYPE=int8
    restart: unless-stopped
    # command: sh -c "flask --app migrate_app db upgrade && python run.py"
